2014-09-25 08:03:49 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:03:49 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:03:49 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:04:47 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:04:47 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:04:47 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:04:52 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:04:52 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:04:52 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:05:01 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:05:01 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:05:01 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:05:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:05:50 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:05:50 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:06:18 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3479): ConnectionManager::getDataSource('default')
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1128): Model->setDataSource('default')
#4 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(3501): Model->setSource('users')
#5 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1357): Model->getDataSource()
#6 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(215): Model->schema()
#7 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Helper/FormHelper.php(467): FormHelper->_introspectModel('User', 'fields')
#8 /opt/local/apache2/htdocs/cakeUnitTest/public/View/Users/login.ctp(17): FormHelper->create('User', Array)
#9 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(948): include('/opt/local/apac...')
#10 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(910): View->_evaluate('/opt/local/apac...', Array)
#11 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(471): View->_render('/opt/local/apac...')
#12 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(198): Controller->render()
#14 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-09-25 08:06:18 Error: Fatal Error (1): Call to a member function getTrace() on a non-object in [/opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/Elements/exception_stack_trace.ctp, line 24]
2014-09-25 08:06:18 Error: [FatalErrorException] Call to a member function getTrace() on a non-object
Request URL: /cakeUnitTest/public/users/login
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/local/apac...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#2 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/local/apac...', 24, Array)
#3 /opt/local/apache2/htdocs/cakeUnitTest/public/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-25 08:07:22 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:07:22 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:07:24 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:07:24 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:11:47 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:11:47 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:11:54 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:11:54 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:12:29 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:12:29 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:22:36 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 08:22:36 Error: [MissingControllerException] Controller class CakeUnitTestController could not be found.
Exception Attributes: array (
  'class' => 'CakeUnitTestController',
  'plugin' => NULL,
)
Request URL: /cakeUnitTest/public/cakeUnitTest/public/favicon.ico
Stack Trace:
#0 /opt/local/apache2/htdocs/cakeUnitTest/public/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
